# Makefile

################################################################
# File dependencies in the Kestrel compiler
# Author: D. W. Jones
# 
# Omitted $(SLEX)sets.h $(SLEX)symboltable.h $(SLEX)stringpool.h  
# from lexical.o
# 
# Instructions:
#          make         -- will build the Kestrel compiler (later)
#          make testlex -- build the testlex test framework
#          make clean   -- delete all files generated by make
################################################################

#######
# configuration options

# compiler to use
COMPILER = c++

#Organization: src contains all headers and .c files, obj contains the object files that we make
OBJ = obj/
SRC = src/
LEX = lexical/
OLEX = lexical/obj/
SLEX = lexical/src/
PAR = parser/
OPARS = parser/obj/
SPARS = parser/src/
ERR = error/  #Note that we are not using this yet! 


#lexical contains: lexical, stringpool, keywords, symboltable
#######
# primary make target: the kestrel compiler

kestrel: main.o $(OLEX)lexical.o $(OLEX)symboltable.o $(OLEX)stringpool.o $(OLEX)error.o

$(OLEX)lexical.o: $(SLEX)lexical.cpp $(SLEX)lexical.h $(SLEX)error.h $(SLEX)config.h $(SLEX)sets.h $(SLEX)symboltable.h $(SLEX)stringpool.h
	$(COMPILER) -o $(OLEX)lexical.o -c $(SLEX)lexical.cpp

$(OLEX)symboltable.o: $(SLEX)symboltable.cpp $(SLEX)symboltable.h $(SLEX)stringpool.h $(SLEX)config.h $(SLEX)error.h
	$(COMPILER) -o $(OLEX)symboltable.o -c $(SLEX)symboltable.cpp

$(OLEX)stringpool.o: $(SLEX)stringpool.cpp $(SLEX)stringpool.h $(SLEX)config.h $(SLEX)error.h
	$(COMPILER) -o $(OLEX)stringpool.o -c $(SLEX)stringpool.cpp

$(OLEX)error.o: $(SLEX)error.cpp 
	$(COMPILER) -o $(OLEX)error.o -c $(SLEX)error.cpp

######
# secondary make target: testlex, to test the lexical analyzer

testlex: $(OLEX)testlex.o $(OLEX)lexical.o $(OLEX)symboltable.o $(OLEX)stringpool.o $(OLEX)error.o
	$(COMPILER)  -o testlex $(OLEX)testlex.o $(OLEX)lexical.o $(OLEX)error.o $(OLEX)symboltable.o $(OLEX)stringpool.o

$(OLEX)testlex.o: $(SLEX)testlex.cpp $(SLEX)lexical.h $(SLEX)symboltable.h $(SLEX)stringpool.h $(SLEX)config.h
	$(COMPILER) -o $(OLEX)testlex.o  -c $(SLEX)testlex.cpp

######
# secondary make target: clean for cleaning up the project

clean:
	rm $(OLEX)*.o
	rm testlex
	#rm $(OPARSE)*.o          <-This should be uncommented later!
	#rm parser       <-This should be uncommented later!
	#rm kestrel      <-This should be uncommented later!
